### ISSUE TITLE
Batching function 

### ISSUE THREAD

**Issue by DmitryKvant** [KnightNiwrem/telegraf-throttler#12]
I need some same functions but also include batching (https://github.com/SGrondin/bottleneck?tab=readme-ov-file#batching)

**Comment by KnightNiwrem** [comment]
> I need some same functions but also include batching (https://github.com/SGrondin/bottleneck?tab=readme-ov-file#batching)

For.. what use case, exactly?

**Comment by KnightNiwrem** [comment]
Closing due to lack of response
