### ISSUE TITLE
Option to only throttle incoming/outgoing updates

### ISSUE THREAD

**Issue by devadathanmb** [KnightNiwrem/telegraf-throttler#13]
Hey, first of all, thanks for making this awesome plugin.

I have a use case where I need to throttle only outgoing requests, to respect the Telegram official rate limits. But I suppose this is not currently possible in this plugin because it initializes both incoming and outgoing throttlers (correct me if I'm wrong). What I want is something similar to the [transformer-throttler](https://github.com/grammyjs/transformer-throttler) available in grammY.

I suppose this is very much doable but do you have any plans to add this feature? If not I'm ready to work on this issue (if that's okay) and try to get it working but your insights on how to neatly implement this would be valuable. 

Thank you.

**Comment by KnightNiwrem** [comment]
The easiest way to disable incoming throttler is to give it a limit config so wide, that it is de facto unlimited (e.g. minTime 0, maxConcurrent 9999, etc).

If you really want to work on something, it would be better for you to write your own plugin based off grammY's throttler (or even your own original idea). Both throttlers have some issues - e.g. Bottleneck doesn't make it easy to handle graceful exits.

Ideally, you should not even need to throttle outgoing api calls. Instead, the best way to correctly handle 429 is described in https://grammy.dev/advanced/flood.

**Comment by devadathanmb** [comment]
Thanks for the response. 

After going through the link I suppose I would not need a throttler anyways if I already handle 429 errors respectfully. 

Being said that, I suppose there doesn't exist any `auto-retry` plugins for Telegraf as of now right? Is this actually doable in v4 without the transformers setup (which I suppose would be available in v5)

**Comment by devadathanmb** [comment]
Closing this issue since it's out of scope of this project anyways. Thanks once again for responding.
