### ISSUE TITLE
Custom throttling

### ISSUE THREAD

**Issue by ShaydullinRuslan** [KnightNiwrem/telegraf-throttler#4]
I need to loop through a couple of thousand of users and send them all the same message. After 60 messages i get 429 error, so i have been trying to make less requests by configuring throttler. With or withour using telegraf-throttler as middleware i am only able to send 30 messages per second and cant change it, so it seems that outConfig doesnt work, but configuring inConfig works fine.

const inConfig = {
  highWater: 3,
  maxConcurrent: 1,
  minTime: 5000,
}

const outConfig = {
  minTime: 1000,
  reservoir: 5,
  reservoirRefreshAmount: 5,
  reservoirRefreshInterval: 50000,
};
const bot = new Telegraf(config.TOKEN);
const throttler = telegrafThrottler({group: groupConfig, in: inConfig, out: outConfig});

bot.use(throttler);

**Comment by KnightNiwrem** [comment]
Unable to reproduce the issue with the code snippet provided. Probably check that you are using a compatible version of `telegraf-throttler` with a compatible version of `telegraf`?

**Comment by KnightNiwrem** [comment]
Closing this issue because there is no response from issue writer.
