### ISSUE TITLE
Middleware does not activate when calling bot.telegram directly

### ISSUE THREAD

**Issue by 50l3r** [KnightNiwrem/telegraf-throttler#6]
Hi,

I have this class to send messages from group chats wirh "sendPhoto" or "sendMessage"

```
import { Telegraf } from 'telegraf';
import { telegrafThrottler } from 'telegraf-throttler';

const throttler = telegrafThrottler();

class Telegram {
	bot: Telegraf

	constructor(){
		if (!process.env.TELEGRAM_TOKEN) {
			console.error('No se ha definido el token de autenticación del bot')
			process.exit();
		}

		this.bot = new Telegraf(process.env.TELEGRAM_TOKEN);
		this.bot.use(throttler);
	}

	public message(params: Pigeon.Telegram.Message): Promise<void> {
		return new Promise((resolve, reject) => {
			try {
				const image = params.image || '';
				const nick = params.nick ? `<i>${params.nick}</i>` : '';
				const engine = params.engine || ''
				const chatId = params.chatId ? params.chatId : process.env.TELEGRAM_CHATID || ''
				const msg = `${params.msg}\n\n<b>[${engine}]</b> ${nick}`;

				if(image){
					this.bot.telegram.sendPhoto(chatId, image, {
						caption: msg,
						parse_mode: 'HTML'
					}).then(() => {
						console.log("pasa");
						resolve()
					}).catch((err) => {
						console.log("err",err);
						reject(err)
					})
				}else{
					this.bot.telegram.sendPhoto(chatId, msg, {
						parse_mode: 'HTML'
					}).then(() => {
						resolve()
					}).catch((err) => {
						reject(err)
					})
				}
			} catch (err) {
				console.error(err);
				reject(err);
			}
		});
	}
}

export default new Telegram();
```

telegraf version: 4.3.0
telegraf-throttler version: 0.6.0

This is what happens when I try to send many messages in a row (ex: 100) with my bot:

![](https://i.gyazo.com/68c4d2ec066111c62d73f7c3940ef139.gif)
Video: https://i.gyazo.com/68c4d2ec066111c62d73f7c3940ef139.mp4

it seems as if it directly does not work. It doesnt throttle my messages.

**Comment by KnightNiwrem** [comment]
Telegraf-throttler is a middleware. By definition, it only works if you are 1) allowing Telegraf to handle the request, and 2) using `ctx` or `ctx.telegram` to respond.

The same is also true for other middlewares. E.g. If you handle the request yourself, and only using Telegraf for the bot.telegram instance for response, then stuff like session wouldn't be present either.

**Comment by 50l3r** [comment]
How could I use it to directly send messages to a group?

**Comment by KnightNiwrem** [comment]
I recommend that you just use Telegraf, the way that it is intended to be used, instead.

**Comment by 50l3r** [comment]
So how should I send a message to a group without first having any interaction?

**Comment by KnightNiwrem** [comment]
The throttling of those api calls are out of scope for a middleware. In order to throttle them, the throttler must be given an instance of bot, with which it can then modify the callApi method. A middleware is normally only aware of the existence of `ctx` and `ctx.telegram` only.

Even if this library is modified to also throttle calls through `bot.telegram`, the library would still be unable to throttle incoming request for you, as you are handling those on your own (presumably) rather than through Telegraf. In such cases, you are better off using Bottleneck directly to throttle incoming requests and outgoing responses yourself.

**Comment by 50l3r** [comment]
> The throttling of those api calls are out of scope for a middleware. In order to throttle them, the throttler must be given an instance of bot, with which it can then modify the callApi method. A middleware is normally only aware of the existence of `ctx` and `ctx.telegram` only.
> 
> Even if this library is modified to also throttle calls through `bot.telegram`, the library would still be unable to throttle incoming request for you, as you are handling those on your own (presumably) rather than through Telegraf. In such cases, you are better off using Bottleneck directly to throttle incoming requests and outgoing responses yourself.

Much thanks :)
