### ISSUE TITLE
The default errorHandler log a meaningless message

### ISSUE THREAD

**Issue by fengkx** [KnightNiwrem/telegraf-throttler#9]
https://github.com/KnightNiwrem/telegraf-throttler/blob/master/src/index.ts#L67

`InKey` is either `form` or `chat`. which log
`InBound from | ....` or `InBound chat | ....`.

Maybe we should use `inKeyId` https://github.com/KnightNiwrem/telegraf-throttler/blob/master/src/index.ts#L99 here `${inKey} ${inKeyId}` to log the id

**Comment by KnightNiwrem** [comment]
PR is welcome
